[build-system]
requires = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "Thermo-Track"  # Project name (Required)
version = "0.1.0"      # Version (Required)
description = "A local project for Thermo-Track"

[tool.setuptools]
packages = ["core"]